### ISSUE TITLE
F-Droid Inclusion

### ISSUE THREAD

**Issue by Poussinou** [maks/droid-synth#11]
Hi,

Since this app is Apache v2 licensed, are you considering the fact to add it to [F-Droid](https://f-droid.org/)? There is a strong community behind.

You can find some documentation [here](https://f-droid.org/docs/).

Otherwise, if you don't want to work on the inclusion of this app in F-Droid by yourself, would you still agree with the inclusion of your app in F-Droid by the maintainer team?

Also, could you please attach a release apk in your [Release section](https://github.com/maks/droid-synth/releases) from now on, so that folks without Google Play can still download your app? :)

**Comment by maks** [comment]
Thank you for opening this issue. I won't be adding it to F-Droid myself, but I'm happy for someone else to do that.
With releasing a APK for download, I would prefer not to do that until I can setup a mechanism for making sure users that directly download the app can be notified of updates. I'm looking at doing that for a few other open source Android apps that I maintain, so once that is in place, I will do it for Droid Synth as well.

**Comment by guysoft** [comment]
Hey,
So I could try, if I find the time. 
Fdroid checks for updates and also documents a build process.
Its done using this data repository: 
https://gitlab.com/fdroid/fdroiddata
