### ISSUE TITLE
This app is not available for any of your devices

### ISSUE THREAD

**Issue by guysoft** [maks/droid-synth#13]
Any idea why this app is saying so?
I got a Samsung S10e running android 12

**Comment by maks** [comment]
Thank you for raising this issue. I'm not sure why that would be the case, Droid Synth should be available to devices running Android 12. The app is not available on Google Play in all countries/regions, so that may be the reason for you seeing that error message.

**Comment by guysoft** [comment]
Based in Israel not sure if that is an issue :-/

I could take a look at adding it to f-droid. I am just in the process of adding an app I built to it.

**Comment by maks** [comment]
Hi yes, that would be it. 
Yes I am aware of F-Droid, another open src app that I maintain is published there. It would be good to have this app published there too but I don't have time to do that at the moment.
There's no reason for it to be not available in Israel so I've now added it now. Not sure how long it will take for that change to show up on Play, but maybe check in a few hours or a day and it should be available.

**Comment by guysoft** [comment]
Hey, downloads now.
Though I don't see it showing up as a midi-in input on android. Which is what I was looking for.

**Comment by maks** [comment]
@guysoft glad you can see it now.
In regards to midi in, it uses the older style "custom usb" midi apis so you need to plugin your midi controller into your phone before starting droid synth or if you have droid synth running when you plug it in, go to another screen (eg droid synths settings) then back to the main droid synth screen and that should then trigger the OS modal dialog prompting you to give permission for droid synth to access the midi controller.

**Comment by guysoft** [comment]
I was trying to use it with a kivy app I wrote that uses the native android midi lib (adapted that to python BTW):https://github.com/guysoft/midistrum

**Comment by maks** [comment]
Ah I see @guysoft . Yes sorry about that, Droid Synth doesn't make use of Androids MIDI API's that would allow that. I have an issue already for working on that #3 but most likely I'll do that work as part of "Droid Synth 2" which I'm going to build as a cross platform app using Flutter. 

In the meantime as you are doing Android dev yourself, you may want to have a go at using via JNI [the C library I made](https://github.com/maks/synth83) that extracts the fm synth functionality out of this app, which is what I'm using as the basis of the new app I'm building using Flutter. Unfortunately its not well documented at this point as I've been the only one using it, but essentially the fm synth engine just expects to be initialised and then receive small arrays of bytes containing MIDI messages, even loading the patchsets is via MIDI sysex's. You can look at the source here to get an idea of whats involved doing it via JNI, though I changed a little bit the C API in my library and mine is also using Miniaudio as the audio engine.

**Comment by fionn** [comment]
I believe it's also (mistakenly?) not available in Hong Kong.
