### ISSUE TITLE
Suggesting for an option to drag/scroll the keyboard while a key is pressed

### ISSUE THREAD

**Issue by Codereamp** [maks/droid-synth#15]
The idea to have an option (checkbox in the settings) that interpret dragging on the screen while the piano key is pressed as scrolling (as though the upper dot line is pressed at the same time). 

I'm not sure whether it was implemented before, I could not find by googling. Maybe it's not practical after all. I suspected that it might be useful when you playing a tune that should use upper non yet visible keys for future notes and by making small movements while playing existing notes to allow gradually revealing this not yet visible part. Anyway, when one holds a key, nothing happens, he or she might as well scroll a little ;) 

Thanks for supporting this project. I use Dexed plugin often, now it's possible to have interesting syx voices on the go.

**Comment by Codereamp** [comment]
I tried to clone and implement what I described. There are some obstacles with mathematics in how multiply touches should be handled, but with all variants it's no more than a couple of dozens lines in `KeyboardView.java`. The feature more or less works and many performers would find it intuitive. Below is the video of this scrolling in action. 

https://github.com/maks/droid-synth/assets/41295076/d785e118-766c-4285-9f29-e0ec6850dd2a

I can fork and make a pull request if you find it worth considering. If not, that's ok :) If you're interested then maybe another option is possible. I'm not very familiar with android layout ui and all, I can provide  `KeyboardView.java` with a a hard-coded scrolling and you would fine-tune it and make a ui settings suitable for the feature.

**Comment by maks** [comment]
Sorry for the slow response and thank you so much for working on this!
Your demo looks great! I would be very happy to receive a PR contribution for this feature.

I'm actually not planning to do any new work on the current DroidSynth codebase as I have now pulled out the FM synth emulator code into its [own C library](https://github.com/maks/lbmsfa) which I have wrapped in a [Dart package](https://pub.dev/packages/msfa_plugin) that I'm using in a new Flutter app "DroidSynth 2" that will then allow android, ios and desktop apps all from the single codebase. I'm planning to publish an initial version of the Flutter apps repo here on Github soon, though the keyboard UI that it has is quite basic compared to the one in the current version of the app as I mainly use it via a midi keyboard controller, but I'd be happy to get better functionality if you felt like working on porting your code to the Flutter version in the future.

**Comment by maks** [comment]
I've now made the [repo for the flutter based app public](https://github.com/maks/droid_synth_2).

**Comment by Codereamp** [comment]
@maks 
Thanks for your response!

> I'm actually not planning to do any new work on the current DroidSynth codebase ....

This fact probably means I have to implement the feature in full (with the setting), I don't think it would be difficult. Then you just review it and accept if everything is ok.  
Will it be difficult for your to periodically update Google Play version? I also found that this project doesn't exist in F-Droid, maybe introducing it there and making it "F-Droid first" would be less taxing for you? Another variant outside Play /F-Droid world is to release the signed release version at github. I may be wrong, but I could not find the apk here. Some OSS projects at github allows downloading releases for side-loading and this might take less time for you for pull requests from me or others to be implemented.   

> ... as I have now pulled out the FM synth emulator code into its [own C library](https://github.com/maks/lbmsfa) 

The lib should be interesting. Though the link you provided is broken. Either wrong url or your repo is still private. I'm interested in this for Dexed my cartridge management where ideally there should be demo/playing option. Dexed has its own derived version of the library you mentioned, but the more choices the better :) 

> I'm planning to publish an initial version of the Flutter apps repo here on Github soon, though the keyboard UI that it has is quite basic compared to the one in the current version of the app as I mainly use it via a midi keyboard controller, but I'd be happy to get better functionality if you felt like working on porting your code to the Flutter version in the future.

Thanks for the info and for making the first step in publicizing it. I will definitely will have this interesting work in mind. Personally I (probably) as you find the on-screen keyboard too rudimentary, but its main pro is that it comes by default with the device so theoretically is always with me for primitive creative work.  Anyway I will now have in mind that for any advancement I should consider your project-2

**Comment by Codereamp** [comment]
@maks, I did the [PR](https://github.com/maks/droid-synth/pull/16). Probably the setting might be implemented better, I'm not just that familiar with Android/java programming. I hope you will find time to review it and change a little according to your experience. Also video aside, you might try the feature at your fingers and see whether it works for example for you and/or correct (+ introduce) some tweaks.  

Thanks!

**Comment by Codereamp** [comment]
@maks, in case you won't be interested in merging  I created [a release](https://github.com/Codereamp/droid-synth/releases/tag/v1.2) with the feature. I hope it's ok and has not technical/moral conflicts with your actitivites :) My goal is to preserve the feature for installing on my devices and exploring whether it was used before and/or might be used in other projects. As for applying this or something new to your new flutter based project, I think everything is possible. Thanks!
